config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users

  authenticated :user do
    root to: "home#dashboard", as: :authenticated_root
  end

  resources :booking_types
  resources :bookings, except: [:index, :new]

  post "payment-intent", to: "bookings#intent"
  get ":booking_link", to: "users#show", as: :user

  scope '/:booking_link', as: :user do
    resources :bookings, only: [:index, :new]
  end

  resources :webhooks, only: :create
  
  root to: "home#index"
end

app/controllers/booking_types_controller.rb
class BookingTypesController < ApplicationController
  before_action :set_booking_type, only: %i[ show edit update destroy ]

  def index
    @booking_types = current_user.booking_types
  end

  def show
  end

  def new
    @booking_type = current_user.booking_types.new
  end

  def edit
  end

  def create
    @booking_type = current_user.booking_types.new(booking_type_params)

    respond_to do |format|
      if @booking_type.save
        format.html { redirect_to root_path, notice: "Booking type was successfully created." }

      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end

  end

  def update
    respond_to do |format|
      if @booking_type.update(booking_type_params)
        format.html { redirect_to root_path, notice: "Booking type was successfully updated."}
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @booking_type.destroy

    respond_to do |format|
      format.html { redirect_to root_url, notice: "Booking type was successfully destroyed."}
    end
  end

  private

    def set_booking_type
      @booking_type = BookingType.find(params[:id])
    end

    def booking_type_params
      params.require(:booking_type).permit(:name, :location, :description, :color, :duration, :payment_required, :price)
    end
end

app/helpers/booking_types_helper.rb
module BookingTypesHelper
  def duration(type)
      if type.duration == 60
        "1 hr"
      else
        type.duration.to_formatted_s + " mins"
      end
    end

  def price(type)
    if type.price.nil?
      "Gratuit"
    else
      type.price.to_formatted_s + " €"
    end
  end

  def find_username(user_id)
    User.find_by(id: user_id).name
  end
end

app/views/booking_types/_booking_type.html.slim
#{dom_id booking_type}
  = link_to edit_booking_type_path(booking_type), class: "p-6 border shadow-xl rounded-xl block hover:shadow-lg transition ease-in duration-300 relative overflow-hidden" do
    .h-1.w-full.absolute.top-0.left-0.right-0 style="background-color: #{booking_type.color}"
    h3.font-medium.text-2xl
    = booking_type.name
    p.text-gray-500 
      | View booking page
    p 
      = duration(booking_type)

    - if booking_type.payment_required?
      .mt-3.pt-3.border-t
        p
          strong
            | Payment required
        p
          strong
            | Price: 
          = number_to_currency(booking_type.price)

app/views/booking_types/_form.html.slim
= form_with(model: booking_type) do |form| 
  - if booking_type.errors.any?
    #error_explanation.bg-red-50.p-6.rounded.text-red-800
      h2.text-lg.font-semibold.mb-3
        = pluralize(booking_type.errors.count, "error") 
      ul.list-disc.leading-relaxed
        - booking_type.errors.full_messages.each do |message|
          - message
  .mb-6
    = form.label :name, class: label_class
    = form.text_field :name, class: input_class
    
  .mb-6
    = form.label :location, class: label_class 
    = form.text_field :location, class: input_class

  .mb-6
    = form.label :description, class: label_class
    = form.rich_text_area :description, class: input_class

  .mb-6
    = form.label :color, class: label_class 
    = form.text_field :color, class: input_class 

  .mb-6
    = form.label :duration, class: label_class 
    = form.number_field :duration, class: input_class 

  .mb-6.flex.items-center.space-x-2
    = form.check_box :payment_required, class: checkbox_class 
    = form.label :payment_required, class: label_class 

  .mb-6.lg:w-1/4
    = form.label :price, class: label_class 
    = form.number_field :price, class: input_class

  .mb-6.lg
    = form.submit class: button_class(theme: 'primary')

    -  if booking_type.persisted? 
      = link_to "Cancel", booking_type, class: "text-neutral-700 underline inline-block ml-3" 
    - else
      = link_to "Cancel", booking_types_path, class: "text-neutral-700 underline inline-block ml-3"

app/views/booking_types/edit.html.slim
.max-w-3xl.mx-auto.px-4
  .flex.items-center.justify-between.mb-6.flex-wrap
    h1.font-bold.text-3xl.mb-6
      | Edit booking_type
    - if @booking_type.persisted? 
      = button_to 'Destroy', @booking_type, method: :delete, class: "text-red-700 underline", data: { turbo_confirm: 'Are you sure?' }  
    = render 'form', booking_type: @booking_type

app/views/booking_types/index.html.erb
<div class="container mx-auto px-4">
  <div class="flex items-center justify-between flex-wrap mb-6">
    <h1 class="text-3xl font-bold">Bookings</h1>

    <%= link_to new_booking_type_path, class: button_class(theme: "primary") do %>
    Add New Booking type
    <% end %>
  </div>

  <table class="table-auto border-collapse border-slate-400 w-full">
    <thead class="bg-slate-50 dark:bg-slate-700">
      <tr>
        
          <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Name</th>
        
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Location</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Description</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Color</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Duration</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Payment required</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Price</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">User</th>
                
      </tr>
    </thead>

    <tbody>
      <% @booking_types.each do |booking_type| %>
      <%= content_tag :tr, id: dom_id(booking_type), class: dom_class(booking_type) do %>
      
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= link_to booking_type.name, booking_type %></td>
      

              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= booking_type.location %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= booking_type.description %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= booking_type.color %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= booking_type.duration %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= booking_type.payment_required %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= booking_type.price %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= booking_type.user.name.full %></td>
      
      
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/booking_types/new.html.slim
.max-w-3xl.mx-auto.px-4
  .flex.items-center.justify-between
    h1.font-bold.text-3xl.mb-6
      | Créer un évènement

    - if current_user.booking_link?
      = link_to "View events page", user_path(booking_link: current_user.booking_link), class: "text-gray-700 underline"
    
  = render 'form', booking_type: @booking_type

app/views/booking_types/show.html.slim
.items-start.justify-center.block.h-full.grid-cols-1.gap-4.lg:grid.lg:items-center.lg:grid-cols-2
  .relative.flex.items-center.justify-center.h-32.overflow-hidden.lg:h-screen.bg-gradient-to-tr.from-black.to-gray-800
    .inset-auto.z-30.flex.items-center.justify-center.flex-1.w-full.h-auto.font-sans.text-center.text-white.shadow.lg:flex.lg:h-screen.lg:absolute.xl:text-5xl
      h1.font-semibold.text-4xl
        | Balade "#{@booking_type.name}"
  div
    .relative.z-20.px-6.mx-auto.lg:px-12.max-w-lg
      .mb-4.xl:mt-8
        .mt-6.mb-4.lg:mt-0
          - if current_user and current_user.role == 'admin'
            .flex-wrap.lg:flex.items-center.lg:space-x-3
              = link_to booking_types_path, class: button_class(theme: "transparent") do
                |  All Booking_types 
              = link_to edit_booking_type_path(@booking_type), class: button_class(theme:"primary") do
                |  Edit 
          - else 
            = link_to 'Go Back', :back, class: button_class(theme: "primary") 

      ul.text-slate-700
        li
          p.font-semibold
            | Location:
          p
            = @booking_type.location
        li
          p.font-semibold
            | Description:
          p
            = @booking_type.description
        li
          p.font-semibold
            | Duration:
          p
            = duration(@booking_type)
        li
          p.font-semibold
            | Price:
          p
            = price(@booking_type)
        li
          p.font-semibold
            | Organisator:
          p
            = @booking_type.user.name.full