config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users

  authenticated :user do
    root to: "home#dashboard", as: :authenticated_root
  end

  resources :booking_types
  resources :bookings, except: [:index, :new]

  post "payment-intent", to: "bookings#intent"
  get ":booking_link", to: "users#show", as: :user

  scope '/:booking_link', as: :user do
    resources :bookings, only: [:index, :new]
  end

  resources :webhooks, only: :create
  
  root to: "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
    @booking_types = BookingType.all
  end

  def dashboard
    @booking_types = current_user.booking_types
    @bookings = Booking.where(booking_type_id: current_user.booking_type_ids)
  end
end

app/views/home/_booking_type.html.slim
.border.rounded.p-6.shadow-md.bg-slate-50.hover:opacity-50
  h1.text-center.text-3xl
    = booking_type.name
  .my-5
    strong 
      | Lieu: 
    = booking_type.location 
  .my-5
    strong 
      | Durée: 
    = duration(booking_type)
  .my-5
    strong 
      | Prix: 
    = price(booking_type)
  .my-5
    strong 
      | Organisateur: 
    = find_username(booking_type.user_id)

app/views/home/dashboard.html.slim
.container.mx-auto.px-4.pb-32
  .flex.items-center.justify-between.pb-6.border-b
    h1.font-extrabold.text-3xl
      | Dashboard
    = link_to "Create booking type", new_booking_type_path, class: button_class(theme: "primary")
  .py-10.grid.grid-cols-3.gap-6
    = render @booking_types

  - if @bookings.pending.any?
    h3.font-bold.text-2xl.mb-6.mt-10.pt-10.border-t.border-slate-2
      | Pending bookings
    table.w-full.table-collapse
      thead
        th.border.border-slate-300.p-3.text-left.bg-slate-50
          | Status
        th.border.border-slate-300.p-3.text-left.bg-slate-50
          | Name
        th.border.border-slate-300.p-3.text-left.bg-slate-50
          | Email
        th.border.border-slate-300.p-3.text-left.bg-slate-50
          | Starts
        th.border.border-slate-300.p-3.text-left.bg-slate-50
          | Ends
        th.border.border-slate-300.p-3.text-left.bg-slate-50
          | Booking Type
        th.border.border-slate-300.p-3.text-left.bg-slate-50
          | Premium
        th.border.border-slate-300.p-3.text-left.bg-slate-50
          | Paid
      tbody
        = render @bookings.pending

  - if @bookings.approved.any?
    h3.font-bold.text-2xl.mb-6.mt-10.pt-10.border-t.border-slate-2
      | Pending bookings
    table.w-full.table-collapse
      thead
        th.border.border-slate-300.p-3.text-left.bg-slate-50
          | Status
        th.border.border-slate-300.p-3.text-left.bg-slate-50
          | Name
        th.border.border-slate-300.p-3.text-left.bg-slate-50
          | Email
        th.border.border-slate-300.p-3.text-left.bg-slate-50
          | Starts
        th.border.border-slate-300.p-3.text-left.bg-slate-50
          | Ends
        th.border.border-slate-300.p-3.text-left.bg-slate-50
          | Booking Type
        th.border.border-slate-300.p-3.text-left.bg-slate-50
          | Premium
        th.border.border-slate-300.p-3.text-left.bg-slate-50
          | Paid
      tbody
        = render @bookings.approved

  - if @bookings.unapproved.any?
    h3.font-bold.text-2xl.mb-6.mt-10.pt-10.border-t.border-slate-2
      | Unapproved bookings
    table.w-full.table-collapse
      thead
        th.border.border-slate-300.p-3.text-left.bg-slate-50
          | Status
        th.border.border-slate-300.p-3.text-left.bg-slate-50
          | Name
        th.border.border-slate-300.p-3.text-left.bg-slate-50
          | Email
        th.border.border-slate-300.p-3.text-left.bg-slate-50
          | Starts
        th.border.border-slate-300.p-3.text-left.bg-slate-50
          | Ends
        th.border.border-slate-300.p-3.text-left.bg-slate-50
          | Booking Type
        th.border.border-slate-300.p-3.text-left.bg-slate-50
          | Premium
        th.border.border-slate-300.p-3.text-left.bg-slate-50
          | Paid
      tbody
        = render @bookings.unapproved

app/views/home/index.html.slim
.py-10.grid.grid-cols-3.gap-6.m-6
  - @booking_types.each do |booking_type|
    = link_to booking_type_path(id: booking_type.id) do
      = render 'booking_type', booking_type: booking_type